name: Deploy PHP App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo tar -zcvf /data/bkp/glocoach-$(date +"%d-%m-%Y").tar.gz /var/www/html/
          sudo rm -rf /var/www/html/*
        EOF

        scp -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy/

        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo cp -r /tmp/deploy/* /var/www/html/
          sudo cp /data/devops/wp-config.php /var/www/html/
          sudo cp /data/devops/.htaccess /var/www/html/
        EOF
