name: Deploy PHP Website

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    name: Backup and Deploy to /var/www/html
    runs-on: [self-hosted, testrunner]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Backup old site and copy new files
      run: |
        # Backup current site
        sudo tar -zcvf /data/bkp/glocoach-$(date +"%d-%m-%Y").tar.gz /var/www/html/

        # Copy new site files from repo to /var/www/html
        sudo rm -rf /var/www/html/*
        sudo cp -r ./* /var/www/html/

        # Copy wp-config.php and .htaccess from devops directory
        #sudo cp /data/devops/wp-config.php /var/www/html/
        #sudo cp /data/devops/.htaccess /var/www/html/
